import { NextResponse } from "next/server"

// Mock products data - replace with Supabase query
const mockProducts = [
  {
    id: "1",
    name: "Walnut Dining Table",
    description:
      "Elegant walnut dining table crafted with precision joinery and hand-finished to bring out the natural grain.",
    price: 2499,
    category: "Tables",
    wood_type: "Walnut",
    image_url: "/walnut-dining-table-wood-furniture.jpg",
    stock: 5,
    rating: 5,
    reviews_count: 24,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Oak Bar Stool Set",
    description: "Set of four handcrafted oak bar stools with cushioned seats and ergonomic design.",
    price: 899,
    category: "Seating",
    wood_type: "Oak",
    image_url: "/oak-bar-stool-custom-wood.jpg",
    stock: 8,
    rating: 4.8,
    reviews_count: 18,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Cherry Bookshelf",
    description: "Custom cherry wood bookshelf with five shelves and adjustable spacing for optimal storage.",
    price: 1799,
    category: "Storage",
    wood_type: "Cherry",
    image_url: "/cherry-wood-bookshelf-modern-design.jpg",
    stock: 3,
    rating: 5,
    reviews_count: 31,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Maple Coffee Table",
    description: "Handcrafted maple coffee table with a smooth finish and clean contemporary lines.",
    price: 1299,
    category: "Tables",
    wood_type: "Maple",
    image_url: "/maple-coffee-table-handcrafted-wood.jpg",
    stock: 6,
    rating: 4.9,
    reviews_count: 22,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Ash Console Table",
    description: "Minimalist ash wood console table perfect for entryways and living spaces.",
    price: 999,
    category: "Tables",
    wood_type: "Ash",
    image_url: "/placeholder.svg?key=console-table",
    stock: 4,
    rating: 4.7,
    reviews_count: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Leather Wingback Chair",
    description: "Classic wingback chair with solid cherry wood frame and premium leather upholstery.",
    price: 1599,
    category: "Seating",
    wood_type: "Cherry",
    image_url: "/placeholder.svg?key=wingback-chair",
    stock: 2,
    rating: 4.9,
    reviews_count: 28,
    created_at: new Date().toISOString(),
  },
]

export async function GET() {
  return NextResponse.json(mockProducts)
}
